export * from './example1';
export * from './delay/delay';
export * from './digital-sequence/digital-sequence';
export * from './low-resolution-sine/low-resolution-sine';
export { examples as sine } from './sine';
export { examples as changeRange } from './change-range';
export { examples as adsr } from './adsr';
export { examples as schmittTrigger } from './schmitt-trigger';
export { examples as quantizer } from './quantizer';
export { examples as timeQuantizer } from './time-quantizer';
export { examples as twoWaySwitch } from './two-way-switch';
export { examples as crossoverDistortion } from './crossover-distortion';
export { examples as filters } from './filters';
